### ISSUE TITLE
Wont work with Django 1.9

### ISSUE THREAD

**Issue by knehez** [gizmag/django-fsm-log#26]
File "..venv\lib\site-packages\django_fsm_log\backends.py", line 2, in <module>
    from django.core.cache import get_cache
ImportError: cannot import name 'get_cache'

get_cache is not supported in django 1.9

**Comment by hzy** [comment]
pull requests welcome

**Comment by browniebroke** [comment]
Link to doc which provides the new way: https://docs.djangoproject.com/en/1.9/topics/cache/#django.core.cache.caches

**Comment by hzy** [comment]
https://github.com/gizmag/django-fsm-log/pull/27 confirms that this package works under Django 1.9, so I'm closing this issue.
